name: Publish

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
   tags:
   - v*
    
  
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            build_command_tag: mac
            artifact_name: './out/mac/1Mind.app'
            asset_name: 1Mind@$tag.app
          - os: windows-latest
            build_command_tag: win
            artifact_name: './out/win-unpacked/1Mind.exe'
            asset_name: 1Mind$tag.exe

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Pre-Build
      run: |
        npm install
        npm run prod
        
    - name: Build
      run: npm run build:${{ matrix.build_command_tag}}
      
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        release_name: "Demo Release"
        prerelease: true
