name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-Build
      run: |
        npm install
        npm run prod
    - name: Build Mac
      run: |
        npm run build:mac
    - name: Zip Release Mac
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d
      uses: TheDoctor0/zip-release@0.6.0
      with:
        # Filename for archive
        filename: 'mac-release.zip'
        # Base path for archive files
        path: './out/mac/'
    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          mac-release.zip
